name: Create release from date

on:
  workflow_call:

jobs:
  create_release_from_date:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create tag
        uses: actions/github-script@v7
        with: 
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.date.outputs.date }}',
              sha: context.sha
            }).catch(err => {
              if (err.status !== 422) throw err;
              github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/v${{ steps.date.outputs.date }}',
                sha: context.sha
              });
            })

      - name: Download artifacts
        id: download_artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip artifacts
        run: |
          cd ${{ steps.download_artifacts.outputs.download-path }}
          for i in */; do (cd $i; zip -r "../${i%/}.zip" ./); done

      - name: Draft release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.download_artifacts.outputs.download-path }}/*.zip
          tag: v${{ steps.date.outputs.date }}
          draft: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          removeArtifacts: true