name: Create release from project

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string

jobs:
  create_release_from_project:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: package_version
        uses: MWin10/get-csproj-version-fork@v1.9.0
        with:
          file: ${{ inputs.project-path }}

      - name: Create tag
        uses: actions/github-script@v7
        with: 
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.package_version.outputs.version }}',
              sha: context.sha
            }).catch(err => {
              if (err.status !== 422) throw err;
              github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/v${{ steps.package_version.outputs.version }}',
                sha: context.sha
              });
            })

      - name: Download artifacts
        id: download_artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip artifacts
        run: |
          cd ${{ steps.download_artifacts.outputs.download-path }}
          for i in */; do (cd $i; zip -r "../${i%/}.zip" ./); done

      - name: Draft release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.download_artifacts.outputs.download-path }}/*.zip
          tag: v${{ steps.package_version.outputs.version }}
          draft: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          removeArtifacts: true